services:
  # The Postgres Service
  db:
    image: postgres:16-alpine  # Alpine is the smallest version, saving disk and RAM
    container_name: fastapi-db
    environment:
      # Docker will look into your .env file for these variables
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'        # Use max 50% of a single CPU core
          memory: 256M       # Cap RAM at 256MB (Postgres runs fine on this for dev)
        reservations:
          memory: 128M       # Minimum RAM to reserve
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # The FastAPI Service
  api:
    #build: .
    image: xedose/fastapi-app:${IMAGE_TAG}
    container_name: fastapi-app
    ports:
      - "8000:8000"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    environment:
      - DB_CONNECTION=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      # We use 'curl' to ping our own /health endpoint
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  postgres_data: