apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: fastapi
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: fastapi-config
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fastapi-secrets
              key: db-password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: fastapi-config
              key: DB_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: db # Matches the host used in your DB_CONNECTION string
  namespace: fastapi
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432