apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secrets
  namespace: fastapi
type: Opaque
data:
  # Values must be base64 encoded
  db-password: cGFzc3dvcmQxMjM=
  secret-key: VHJoTGlEdHBNVTA1dE5jc08zaTBOTElw
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
  namespace: fastapi
data:
  DB_USER: "rahul_admin"
  DB_NAME: "ultimate_platform"
  ALGORITHM: "HS256"